env: "local" # local, dev, prod

storage:
  host: "localhost"
  port: 5432
  user: "golang_user"
  password: "golang_pass"
  dbname: "golang_db"
  sslmode: "disable"

http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timout: 60s
